// This page shows the activity logs for the user's account
import { Suspense } from 'react';
import {
  AlertCircle,
  Lock,
  LogOut,
  type LucideIcon,
  Settings,
  UserCog,
  UserMinus,
  UserPlus,
} from 'lucide-react';
import { getActivityLogs } from '@/lib/db/queries';
import { ActivityType } from '@/lib/db/schema';

const iconMap: Record<ActivityType, LucideIcon> = {
  [ActivityType.SIGN_UP]: UserPlus,
  [ActivityType.SIGN_IN]: UserCog,
  [ActivityType.SIGN_OUT]: LogOut,
  [ActivityType.UPDATE_PASSWORD]: Lock,
  [ActivityType.DELETE_ACCOUNT]: UserMinus,
  [ActivityType.UPDATE_ACCOUNT]: Settings,
};

function getRelativeTime(date: Date) {
  const now = new Date();
  const diffInSeconds = Math.floor((now.getTime() - date.getTime()) / 1000);

  if (diffInSeconds < 60) return 'just now';
  if (diffInSeconds < 3600) return `${Math.floor(diffInSeconds / 60)} minutes ago`;
  if (diffInSeconds < 86400) return `${Math.floor(diffInSeconds / 3600)} hours ago`;
  if (diffInSeconds < 604800) return `${Math.floor(diffInSeconds / 86400)} days ago`;
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

function formatAction(action: ActivityType): string {
  switch (action) {
    case ActivityType.SIGN_UP:
      return 'You signed up';
    case ActivityType.SIGN_IN:
      return 'You signed in';
    case ActivityType.SIGN_OUT:
      return 'You signed out';
    case ActivityType.UPDATE_PASSWORD:
      return 'You changed your password';
    case ActivityType.DELETE_ACCOUNT:
      return 'You deleted your account';
    case ActivityType.UPDATE_ACCOUNT:
      return 'You updated your account';
    default:
      return 'Unknown action occurred';
  }
}

function ActivitySkeleton() {
  return <div className="min-h-96 animate-pulse rounded-sm bg-slate-800" />;
}

async function ActivityLog() {
  const logs = await getActivityLogs();
  if (!logs || logs.length === 0) {
    return (
      <div className="flex h-96 flex-col items-center justify-center rounded-sm bg-slate-800 text-center">
        <AlertCircle className="text-light-mustard mb-4 h-12 w-12" />
        <h3 className="mb-2 text-lg font-semibold">No activity yet</h3>
        <p className="text-muted-foreground max-w-sm text-sm">
          When you perform actions like signing in or updating your account, they&apos;ll appear
          here.
        </p>
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-2 rounded-sm bg-slate-800">
      {logs.map((log) => {
        const Icon = iconMap[log.action as ActivityType] || Settings;
        const formattedAction = formatAction(log.action as ActivityType);

        return (
          <div key={log.id} className="rounded-sm border-b border-gray-500/50">
            <div className="flex flex-row items-center gap-2 p-4">
              <Icon className="size-4 text-orange-600" />
              <div className="flex flex-col gap-1">
                <p className="text-sm font-medium">
                  {formattedAction} {log.ipAddress && ` from ${log.city}, ${log.region}`}
                </p>
                <p className="text-muted-foreground text-xs">
                  {getRelativeTime(new Date(log.timestamp))}
                </p>
              </div>
            </div>
          </div>
        );
      })}
    </div>
  );
}

export default async function ActivityPage() {
  return (
    <main className="min-h-[calc(100dvh-7.5rem)] bg-slate-900 text-gray-100">
      <header className="border-b border-gray-500/50">
        <div className="mx-auto flex max-w-6xl flex-col gap-2 px-4 py-8">
          <h1 className="text-4xl font-bold">Activity</h1>
          <p className="text-gray-400">Autogenerated activity logs for your account.</p>
        </div>
      </header>

      <div className="mx-auto flex max-w-6xl flex-col gap-2 px-4 py-8">
        <Suspense fallback={<ActivitySkeleton />}>
          <ActivityLog />
        </Suspense>
      </div>
    </main>
  );
}
