-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "activity_logs" (
	"id" bigint CONSTRAINT "activity_logs_id_key" UNIQUE GENERATED BY DEFAULT AS IDENTITY (sequence name "activity_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"uuid" uuid NOT NULL,
	"action" text NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"country" text,
	"country_code" text,
	"region" text,
	"city" text,
	"latitude" text,
	"longitude" text,
	"zip" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "activity_logs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "cron" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cron_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "cron" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "members" (
	"uuid" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	"id" bigint CONSTRAINT "members_id_key" UNIQUE GENERATED BY DEFAULT AS IDENTITY (sequence name "members_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"email" text NOT NULL CONSTRAINT "members_email_key" UNIQUE,
	"password" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "members" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "profile_links" (
	"uuid" uuid,
	"platform" text,
	"url" text NOT NULL,
	"visible" boolean DEFAULT false NOT NULL,
	CONSTRAINT "profile_links_pkey" PRIMARY KEY("uuid","platform")
);
--> statement-breakpoint
ALTER TABLE "profile_links" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "profiles" (
	"uuid" uuid PRIMARY KEY,
	"username" text NOT NULL CONSTRAINT "profiles_username_key" UNIQUE,
	"display_name" text,
	"bio" text,
	"terms" smallint[],
	"teams" text[],
	"roles" text[],
	"avatar_url" text
);
--> statement-breakpoint
ALTER TABLE "profiles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "reset_tokens" (
	"uuid" uuid PRIMARY KEY,
	"token" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "reset_tokens" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE INDEX "profile_links_uuid_idx" ON "profile_links" ("uuid");--> statement-breakpoint
CREATE INDEX "profiles_uuid_idx" ON "profiles" ("uuid");--> statement-breakpoint
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_uuid_fkey" FOREIGN KEY ("uuid") REFERENCES "members"("uuid") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "reset_tokens" ADD CONSTRAINT "reset_tokens_uuid_fkey" FOREIGN KEY ("uuid") REFERENCES "members"("uuid") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "activity_logs" ADD CONSTRAINT "activity_logs_uuid_fkey" FOREIGN KEY ("uuid") REFERENCES "members"("uuid") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "profile_links" ADD CONSTRAINT "profile_links_uuid_fkey" FOREIGN KEY ("uuid") REFERENCES "profiles"("uuid") ON DELETE CASCADE;
*/